---
title: Hoe de Sense HAT-extensie toe te voegen
hero_image: images/banner.png
description: Hoe de Sense HAT-extensie toe te voegen
version: 4
listed: false
copyedit: false
last_tested: "2019-09-12"
steps:
  - title: Inleiding

