title: How to add the Sense HAT extension
hero_image: images/banner.png
description: How to add the Sense HAT extension
version: 4
listed: false
copyedit: false
last_tested: "2019-09-12"
steps:
  - title: Introduction

