title: rpi-scratch3-add-sensehat-extension
hero_image: images/banner.png
description: rpi-scratch3-add-sensehat-extension description
version: 4
listed: false
copyedit: false
last_tested: "2019-09-12"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
