---
title: Sut i ychwanegu'r estyniad Sense HAT
hero_image: images/banner.png
description: Sut i ychwanegu'r estyniad Sense HAT
version: 4
listed: false
copyedit: false
last_tested: "2019-09-12"
steps:
  - title: Cyflwyniad

