---
title: Como adicionar a extensão Sense HAT
hero_image: images/banner.png
description: Como adicionar a extensão Sense HAT
version: 4
listed: false
copyedit: false
last_tested: "2019-09-12"
steps:
  - 
    title: Introdução

