---
title: Cómo agregar la extensión Sense HAT
hero_image: images/banner.png
description: Cómo agregar la extensión Sense HAT
version: 4
listed: false
copyedit: false
last_tested: "2019-09-12"
steps:
  - 
    title: Introducción

