---
title: Comment ajouter l'extension Sense HAT
hero_image: images/banner.png
description: Comment ajouter l'extension Sense HAT
version: 4
listed: false
copyedit: false
last_tested: "2019-09-12"
steps:
  - 
    title: Introduction

